# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogReg', '0002_auto_20170603_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('plan', models.TextField()),
                ('travel_start_date', models.DateTimeField()),
                ('travel_end_date', models.DateTimeField()),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='LogReg.userDB')),
                ('travelers', models.ManyToManyField(related_name='trip_travelers', to='LogReg.userDB')),
            ],
        ),
    ]
